import type { Metadata } from "next";
import { Geist, Geist_Mono, Delicious_Handrawn } from "next/font/google";
import "./globals.css";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import Header from "./header/page";
import LoadingPage from "@/components/loadingPage";

/*
* RootLayout Component
* This is the root-level layout for the entire Next.js application (App Router).
* It wraps all pages, setting up the necessary HTML structure, global styles, metadata,and essential providers like Clerk.
* It ensures the Header is present on all pages and handles the loading state for the Clerk authentication.
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const deliciousHandrawn = Delicious_Handrawn({
  weight: "400", // Delicious Handrawn has only 400 thickness
  subsets: ["latin"],
  display: "swap",
  variable: "--font-delicious-handrawn", // CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          root: {
            fontFamily: `var(${geistMono.variable}), var(${geistSans.variable} antialiased)`,
          },
        },
      }}
    >
      <html lang="en">
        <body
          className={` ${geistMono.variable} ${geistSans.variable} ${deliciousHandrawn.variable} antialiased `}
        >
          <ClerkLoading>
            <LoadingPage />
          </ClerkLoading>
          <ClerkLoaded>
            {/* display main contents from the top when mobile screen */}
            <div className="relative w-full h16">
              <Header />
              <div className="pt-8 md:pt-16">
                <div className="max-w-screen-xl mx-auto px-4 sm:px-6 lg:px-8">
                  {children}
                </div>
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
